spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main.banner-mode: "off"
  jersey:
    application-path: /

server:
  servlet:
    context-path: /person/arbeidsforhold-api

logging:
  level:
    org.springframework: INFO
    org.glassfish: INFO
    no.nav: INFO

http.proxy: http://webproxy-nais.nav.no:8088

no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: ${AAD_B2C_DISCOVERY_URL}
    acceptedaudience: ${AAD_B2C_CLIENTID_USERNAME}
    cookie_name: selvbetjening-idtoken
