apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: arbeidsforhold-api
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /person/arbeidsforhold-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/arbeidsforhold-api/internal/isAlive
    initialDelay: 10
  prometheus:
    enabled: true
    path: /person/arbeidsforhold-api/internal/metrics
  replicas:
    min: {{ min-replicas }}
    max: {{ max-replicas }}
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: {{ aareg-host }}
        - host: {{ ereg-host }}
    inbound:
      rules:
        - application: aareg-innsyn-arbeidsgiver
          namespace: arbeidsforhold
  ingresses:
  {{#each ingresses}}
     - "{{this}}"
         {{/each}}
  envFrom:
    - secret: arbeidsforhold-api-secret
  secureLogs:
    enabled: true
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 384Mi
