apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: arbeidsforhold-api
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /person/arbeidsforhold-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/arbeidsforhold-api/internal/isAlive
    initialDelay: 10
  prometheus:
    enabled: true
    path: /person/arbeidsforhold-api/internal/metrics
  replicas:
    min: 2
    max: 4
  tokenx:
    enabled: true
  accessPolicy:
    rules:
      - application: {{ aareg-app-name }}
        namespace: personbruker
        cluster: {{ fss-cluster }}
    outbound:
      external:
        - host: {{ aareg-host }}
  ingresses:
  {{#each ingresses}}
     - "{{this}}"
         {{/each}}
  envFrom:
    - configmap: loginservice-idporten
    - secret: arbeidsforhold-api-secret
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 384Mi
